#Build Environment
From node:10.16-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . /app

RUN npm run build

#Production Environment
FROM nginx:1.16-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
